version: '3.8'

services:
  postgres_service:
    image: postgres
    environment:
      POSTGRES_DB: BotanicalBuddy
      POSTGRES_USER: BotanicalBuddy
      POSTGRES_PASSWORD: BotanicalBuddy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    